[package]
name = "MovernancePad"
version = "1.0.0"
authors = []

[addresses]
aptos_framework = "0x1"
aptos_std = "0x1"
MovernancePad = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
